version: '2'
services:
    proyecto-app:
        image: proyecto
        external_links:
            - proyecto-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/proyecto?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proyecto-mysql:
        extends:
            file: mysql.yml
            service: proyecto-mysql
